import{a as k,i as f,S as $}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v="41640430-3528202645bdb0a9dd97623d3";let i=1,d="",g=0,m=0;const h=document.querySelector("#searchForm"),M=document.querySelector("#searchInput"),y=document.getElementById("gallery"),c=document.querySelector(".loader"),u=document.getElementById("loadMoreBtn");h.addEventListener("submit",_);u.addEventListener("click",x);async function _(e){e.preventDefault();const r=M.value.trim();if(r){d=r,i=1,S(c);try{const{images:n,total:a}=await p(d,i);g=a,b(n),await w(n.length)}catch(n){L(n)}finally{I(c),h.reset()}}}async function x(){S(c),i++;try{const{images:e,total:r}=await p(d,i);g=r,b(e,!0),await w(e.length),window.scrollBy({top:m*2,behavior:"smooth"})}catch(e){L(e)}finally{I(c)}}async function p(e,r){const a=`https://pixabay.com/api/?key=${v}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${40}`;try{const t=await k.get(a);if(t.status!==200)throw new Error("Network response was not ok");const{hits:o,totalHits:s}=t.data;if(o.length>0&&i===1){const l=document.querySelector(".gallery__item");l&&(m=l.getBoundingClientRect().height)}return{images:o,total:s}}catch(t){throw t}}async function w(e){i*40>=g?(u.style.display="none",e>0&&await f.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#3e5c40",position:"topRight",messageColor:"#fff",messageSize:"14px",timeout:3e3,maxWidth:400,transitionIn:"fadeInLeft",transitionOut:"fadeOut"})):u.style.display="block"}function b(e,r=!1){if(r||(y.innerHTML=""),e.length===0&&i===1){f.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#85380f",position:"topRight",messageColor:"#fff",messageSize:"14px",timeout:3e3,maxWidth:400,transitionIn:"fadeInLeft",transitionOut:"fadeOut"}),u.style.display="none";return}const n=E(e);y.innerHTML+=n,new $("#gallery a",{captionsData:"alt",captionPosition:"bottom"}).refresh()}function E(e){return e.map(({webformatURL:r,tags:n,likes:a,views:t,comments:o,downloads:s,largeImageURL:l})=>`
    <li class="gallery__item">
      <a class="gallery__link" href="${l}">
        <img class="gallery__image" src="${r}" alt="${n}" />
      </a>
      <div class="image-info">
        <span>Likes: ${a}</span>
        <span>Views: ${t}</span>
        <span>Comments: ${o}</span>
        <span>Downloads: ${s}</span>
      </div>
    </li>`).join("")}function L(e){console.error("Error fetching images:",e);const r=e.response&&e.response.status===404?"Sorry, there are no images matching your search query. Please try again!":"An error occurred while fetching images. Please try again later.";f.error({title:"Error",message:r})}function S(e){e.style.display="block"}function I(e){e.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
